PS D:\justinwj\Solutions\Visio Diagram Generator> git diff --no-index -- "tests/fixtures/render/invSys/callgraph/invSys.callgraph.diagnostics.json" "out/fixtures/invSys/callgraph/invSys.callgraph.diagnostics.json"
diff --git a/tests/fixtures/render/invSys/callgraph/invSys.callgraph.diagnostics.json b/out/fixtures/invSys/callgraph/invSys.callgraph.diagnostics.json
index ee149bc..d187e32 100644
--- a/tests/fixtures/render/invSys/callgraph/invSys.callgraph.diagnostics.json
+++ b/out/fixtures/invSys/callgraph/invSys.callgraph.diagnostics.json
@@ -1,530 +1,818 @@
 {
   "Version": "1.0",
   "Metrics": {
-    "LayoutOutputMode": "view",
-    "LayoutCanvasWidth": 31.4500008,
-    "LayoutCanvasHeight": 25.5999985,
-    "LayoutNodeCount": 210,
-    "LayoutModuleCount": 37,
-    "LayoutContainerCount": 37,
-    "LayerCount": 1,
-    "LayerCrowdingCount": 0,
-    "LayerOverflowCount": 0,
-    "BridgeCount": 0,
     "ConnectorCount": 1684,
-    "StraightLineCrossings": 1266997,
+    "StraightLineCrossings": 1276104,
     "PageHeight": 8.5,
     "UsableHeight": 7.5,
-    "ModuleCount": 0,
-    "SegmentCount": 0,
-    "SegmentDelta": 0,
-    "SplitModuleCount": 0,
-    "AverageSegmentsPerModule": 0,
-    "PlannerPageCount": 7,
-    "PlannerAverageModulesPerPage": 5.2857142857142856,
-    "PlannerAverageConnectorsPerPage": 24.285714285714285,
-    "PlannerMaxOccupancyPercent": 0,
-    "PlannerMaxConnectorsPerPage": 62,
-    "PageOverflowCount": 3,
-    "PageCrowdingCount": 0,
-    "LaneOverflowCount": 0,
-    "LaneCrowdingCount": 5,
-    "ContainerOverflowCount": 25,
-    "PartialRender": true,
-    "ConnectorOverLimitPageCount": 0,
-    "PagesWithPartialRender": 3,
-    "TruncatedNodeCount": 0,
-    "SkippedModules": [],
-    "Pages": [
-      {
-        "Index": 1,
-        "Name": "clsBulkSnapshot, frmAdminControls, frmCreateDeleteUser, frmEditUser, frmItemSearch#part1, frmItemSearch#part2",
-        "Nodes": 31,
-        "Connectors": 3,
-        "SkippedConnectors": 0,
-        "Overflow": false,
-        "ConnectorLimit": 400,
-        "ConnectorOverLimit": 0,
-        "ModuleCount": 6,
-        "Partial": true,
-        "LaneCrowdingWarnings": 1,
-        "LaneCrowdingErrors": 0,
-        "PageCrowding": false,
-        "PageOverflow": true,
-        "TruncatedNodes": 0
-      },
-      {
-        "Index": 2,
-        "Name": "frmLogin, frmReceivedTally, frmShipmentsTally, InventoryManagement, modAdmin, modErrorHandler",
-        "Nodes": 25,
-        "Connectors": 2,
-        "SkippedConnectors": 0,