name: VBA CLI Smoke

on:
  push:
    paths:
      - 'src/VDG.VBA.CLI/**'
      - 'tools/vba2json.ps1'
      - 'tools/vba-ir2diagram.ps1'
      - 'tests/fixtures/vba/**'
      - 'docs/VDG_VBA_CLI.md'
  pull_request:
    paths:
      - 'src/VDG.VBA.CLI/**'
      - 'tools/vba2json.ps1'
      - 'tools/vba-ir2diagram.ps1'
      - 'tests/fixtures/vba/**'
      - 'docs/VDG_VBA_CLI.md'

jobs:
  smoke:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
      - name: Build CLI
        run: dotnet build src/VDG.VBA.CLI -c Release
      - name: End-to-end
        shell: pwsh
        run: |
          dotnet run --project src/VDG.VBA.CLI -- vba2json --in tests/fixtures/vba/cross_module_calls --out out/gh_ir.json
          ./tools/ir-validate.ps1 -InputPath out/gh_ir.json
          dotnet run --project src/VDG.VBA.CLI -- ir2diagram --in out/gh_ir.json --out out/gh_diagram.json
          test -s out/gh_diagram.json

